import{Suspense,lazy,useEffect,useMemo,useRef,useState}from'react';import{Activity,ArrowDownToLine,BookOpen,Check,ChevronDown,ChevronLeft,ChevronRight,CircleHelp,Clock3,FileMusic,FolderOpen,Headphones,Keyboard,Music2,Pause,Play,Plus,Power,RotateCcw,Settings,Square,Upload,Volume2,Wifi}from'lucide-react';
import{parseMidi}from'../midi/parseMidi';import{connectMidi,listMidiInputs,type MidiDevice}from'../midi/webMidi';import{PracticeEngine}from'../practice/engine';import type{HandSelection,Song,SongNote}from'../model/song';import{allNotes,notesForHand}from'../model/song';import{library}from'../storage/library';
import{SongPlayback}from'../audio/SongPlayback';
const ScoreView=lazy(()=>import('../components/ScoreView').then(module=>({default:module.ScoreView})));
type Mode='practice'|'follow'|'playback';const pitchNames=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
function keyCenter(pitch:number){let whites=0;for(let p=21;p<=pitch;p++){const black=[1,3,6,8,10].includes(p%12);if(p===pitch)return black?whites*22:whites*22+11;if(!black)whites++;}return 0;}
function lowerBoundTime(notes:SongNote[],time:number){let low=0,high=notes.length;while(low<high){const mid=(low+high)>>1;if(notes[mid].startTime<time)low=mid+1;else high=mid;}return low;}
function playbackGroupAt(notes:SongNote[],time:number){let i=lowerBoundTime(notes,time);if(i>0&&notes[i-1].startTime+notes[i-1].duration>time)i--;const anchor=notes[i];if(!anchor)return[];const start=lowerBoundTime(notes,anchor.startTime);const result:SongNote[]=[];for(let j=start;j<notes.length&&notes[j].startTime===anchor.startTime;j++)result.push(notes[j]);return result;}
function notesAhead(notes:SongNote[],time:number,windowSeconds:number){const result:SongNote[]=[];for(let i=lowerBoundTime(notes,Math.max(0,time-.08));i<notes.length&&notes[i].startTime<=time+windowSeconds;i++)result.push(notes[i]);return result;}
function KeyboardDeck({expected,played,correct,wrong,mode,groups,notes,eventIndex,playbackTime}:{expected:number[];played:number[];correct:number[];wrong:number[];mode:Mode;groups:SongNote[][];notes:SongNote[];eventIndex:number;playbackTime:number}){
 const viewport=useRef<HTMLDivElement>(null);useEffect(()=>{const p=expected[0];if(p===undefined||!viewport.current)return;const box=viewport.current;box.scrollTo({left:Math.max(0,keyCenter(p)-box.clientWidth/2),behavior:'smooth'});},[expected.join(',')]);
 const falling=mode==='playback'
  ?notesAhead(notes,playbackTime,3.2).map(note=>({note,top:Math.max(0,74-Math.max(0,note.startTime-playbackTime)/3.2*70),height:Math.max(10,Math.min(28,note.duration/3.2*70))}))
  :groups.slice(eventIndex,eventIndex+6).flatMap((group,i)=>group.map(note=>({note,top:74-i*13,height:13})));
 return <div className="keyboard-deck" ref={viewport}><div className="falling-wrap"><div className="falling-roll"><div className="falling-lane-grid"/><div className="falling-target"/>{falling.map(({note,top,height})=><div key={note.id} className={`falling-note ${expected.includes(note.pitch)?'falling-current':''}`} style={{left:keyCenter(note.pitch)-8,top:`${top}%`,height}} title={`${pitchNames[note.pitch%12]}${Math.floor(note.pitch/12)-1}`}><span>{pitchNames[note.pitch%12]}{Math.floor(note.pitch/12)-1}</span></div>)}</div></div><div className="piano-wrap"><div className="piano" role="img" aria-label="Full 88-key piano keyboard, horizontally scrollable from A0 to C8">{Array.from({length:88},(_,i)=>21+i).map(p=>{const black=[1,3,6,8,10].includes(p%12);const state=wrong.includes(p)?'wrong':correct.includes(p)?'correct':played.includes(p)?'played':expected.includes(p)?'expected':'';return <div key={p} data-midi-pitch={p} className={`key ${black?'black':'white'} ${state}`} title={`${pitchNames[p%12]}${Math.floor(p/12)-1}`}>{!black&&p%12===0&&<span>{pitchNames[p%12]}{Math.floor(p/12)-1}</span>}</div>})}</div></div></div>
}
export default function App(){
 const[songs,setSongs]=useState<Song[]>([]),[song,setSong]=useState<Song|null>(null),[mode,setMode]=useState<Mode>('practice'),[tempo,setTempo]=useState(100),[metronome,setMetronome]=useState(false),[hand,setHand]=useState<'both'|'left'|'right'>('both'),[devices,setDevices]=useState<MidiDevice[]>([]),[selectedDevice,setSelectedDevice]=useState(''),[deviceError,setDeviceError]=useState(''),[connected,setConnected]=useState(false),[pedalDown,setPedalDown]=useState(false),[played,setPlayed]=useState<number[]>([]),[flash,setFlash]=useState<'correct'|'wrong'|''>(''),[loop,setLoop]=useState(false),[playing,setPlaying]=useState(false),[playbackTime,setPlaybackTime]=useState(0),[renaming,setRenaming]=useState(false),[title,setTitle]=useState(''),[renamingSong,setRenamingSong]=useState(false);
 const inputRef=useRef<HTMLInputElement>(null);const cleanup=useRef<(()=>void)|null>(null);const player=useRef<SongPlayback|null>(null);const chordPitches=useRef<Set<number>>(new Set());const chordTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const engine=useMemo(()=>song?new PracticeEngine(song,undefined,hand):null,[song,hand]);const engineRef=useRef<PracticeEngine|null>(engine);engineRef.current=engine;const [,refresh]=useState(0);
 useEffect(()=>{player.current=new SongPlayback();library.songs.toArray().then(rows=>{setSongs(rows.sort((a,b)=>b.createdAt-a.createdAt));if(rows.length){setSong(rows[0]);setTitle(rows[0].title);}});return()=>{cleanup.current?.();player.current?.stop();};},[]);
 useEffect(()=>{if(!song)return;library.songs.put(song).catch(()=>{});},[song]);
 const current=engine?.current;const expected=current?.map(n=>n.pitch)??[];const currentIds=current?.map(n=>n.id)??[];
 async function playFrom(time:number,speedPercent=tempo,hands:HandSelection=hand){if(!song||!player.current)return;try{await player.current.play(song,time,speedPercent/100,setPlaybackTime,()=>{setPlaying(false);setPlaybackTime(0);},hands);setPlaying(true);}catch(e){setDeviceError(e instanceof Error?e.message:'Could not start audio playback.');}}
 function selectHand(next:HandSelection){if(next===hand)return;const wasPlaying=playing;let time=playbackTime;if(wasPlaying&&player.current){time=player.current.pause();setPlaybackTime(time);setPlaying(false);}chordPitches.current.clear();setPlayed([]);setHand(next);if(wasPlaying)void playFrom(time,tempo,next);}
 async function togglePlayback(){if(playing&&player.current){const time=player.current.pause();setPlaybackTime(time);setPlaying(false);}else await playFrom(playbackTime);}
 function stopPlayback(reset=true){player.current?.stop();setPlaying(false);if(reset)setPlaybackTime(0);}
 function selectMode(next:Mode){if(next!=='playback'&&playing)stopPlayback(false);setMode(next);}
 function changeTempo(value:number){const next=Math.max(50,Math.min(150,value));let time=playbackTime;if(playing&&player.current){time=player.current.pause();setPlaying(false);}setTempo(next);if(playing)void playFrom(time,next);}
 async function importFile(file?:File){if(!file)return;try{stopPlayback();const parsed=parseMidi(await file.arrayBuffer(),file.name.replace(/\.midi?$/i,''));parsed.sourceName=file.name;setSong(parsed);setTitle(parsed.title);setSongs(s=>[parsed,...s.filter(x=>x.id!==parsed.id)]);setDeviceError('');}catch(e){setDeviceError(e instanceof Error?e.message:'Could not import this MIDI file.');}}
 async function setupMidi(deviceId=selectedDevice){cleanup.current?.();setDeviceError('');cleanup.current=await connectMidi((pitch,on)=>{setPlayed(p=>on?[...new Set([...p,pitch])]:p.filter(x=>x!==pitch));const activeEngine=engineRef.current;if(on&&activeEngine){chordPitches.current.add(pitch);if(chordTimer.current)clearTimeout(chordTimer.current);const result=activeEngine.input([...chordPitches.current]);setFlash(result.correct?'correct':'wrong');if(result.correct){chordPitches.current.clear();setPlayed([pitch]);refresh(v=>v+1);setTimeout(()=>setPlayed([]),220);}else{chordTimer.current=setTimeout(()=>{chordPitches.current.clear();},activeEngine.policy.chordToleranceMs);setTimeout(()=>setFlash(''),280);}}},()=>{const next=listMidiInputs();setDevices(next);setConnected(next.some(d=>d.state==='connected'&&(!deviceId||d.id===deviceId)));},setDeviceError,deviceId,down=>setPedalDown(down));setDevices(listMidiInputs());setConnected(listMidiInputs().some(d=>d.state==='connected'&&(!deviceId||d.id===deviceId)));}
 function chooseSong(item:Song){stopPlayback();setSong(item);setTitle(item.title);engine?.restart();refresh(v=>v+1)}
 function restart(){stopPlayback();engine?.restart();setPlayed([]);setFlash('');refresh(v=>v+1)}
 function step(delta:number){if(mode==='playback'&&song){const times=[...new Set(allNotes(song).map(n=>n.startTime))].sort((a,b)=>a-b);if(!times.length)return;const target=delta>0?(times.find(t=>t>playbackTime+.01)??times.at(-1)!):(times.filter(t=>t<playbackTime-.01).at(-1)??times[0]);setPlaybackTime(target);if(playing)void playFrom(target);return;}engine?.seek((engine.index||0)+delta);setPlayed([]);refresh(v=>v+1)}
 function rename(){if(!song)return;if(renamingSong){const updated={...song,title:title.trim()||song.title};setSong(updated);setSongs(s=>s.map(x=>x.id===song.id?updated:x));}setRenamingSong(!renamingSong)}
 async function removeSong(item:Song){await library.songs.delete(item.id);const left=songs.filter(s=>s.id!==item.id);setSongs(left);if(song?.id===item.id){stopPlayback();setSong(left[0]??null)}}
 const measures=song?.measures.length??0;const notes=useMemo(()=>song?allNotes(song):[],[song]);const handNotes=useMemo(()=>notesForHand(notes,hand),[notes,hand]);const noteCount=notes.length;const songDuration=useMemo(()=>notes.reduce((end,n)=>Math.max(end,n.startTime+n.duration),0),[notes]);const playbackGroup=mode==='playback'?playbackGroupAt(handNotes,playbackTime):[];const visibleNotes=mode==='playback'?playbackGroup:current??[];const visibleIds=visibleNotes.map(n=>n.id);const visibleExpected=visibleNotes.map(n=>n.pitch);const progress=mode==='playback'&&songDuration?Math.min(1,playbackTime/songDuration):(engine?.progress??0);
 return <div className="app-shell">
 <header className="topbar"><div className="brand"><div className="brand-mark"><Music2 size={19}/></div><span>Piano<span className="brand-light">Practice</span></span><span className="beta">STUDIO</span></div><div className="top-center"><span className="live-dot"/>LOCAL SESSION <i/> {connected?'MIDI CONNECTED':'MIDI AVAILABLE'}</div><div className="top-actions"><button className="icon-button" aria-label="Help"><CircleHelp size={17}/></button><button className="avatar">A</button></div></header>
 <main className="workspace">
  <aside className="library-panel"><div className="panel-heading"><div><div className="eyebrow">YOUR SPACE</div><h2>Library</h2></div><button className="icon-button faint" onClick={()=>inputRef.current?.click()} title="Import MIDI"><Plus size={17}/></button></div><button className="import-card" onClick={()=>inputRef.current?.click()}><span className="upload-icon"><Upload size={17}/></span><span><b>Import MIDI file</b><small>Drop a .mid or .midi file</small></span><ChevronRight size={15}/></button><input ref={inputRef} className="hidden" type="file" accept=".mid,.midi,audio/midi" onChange={e=>{void importFile(e.target.files?.[0]);e.currentTarget.value='';}}/><div className="list-label">RECENT SONGS <span>{songs.length}</span></div><div className="song-list">{songs.map((item,i)=><div key={item.id} className={`song-row ${song?.id===item.id?'selected':''}`}><button className="song-select" onClick={()=>chooseSong(item)}><span className={`song-cover cover-${i%4}`}><Music2 size={15}/></span><span className="song-text"><b>{item.title}</b><small>{item.tracks.length} tracks · {item.measures.length} measures</small></span></button><button className="song-menu" title="Delete song" onClick={()=>void removeSong(item)}>×</button></div>)}</div><div className="library-bottom"><div className="storage-note"><span className="storage-dot"/><span>Saved on this device</span></div><button className="text-button" onClick={()=>{if(song){setTitle(song.title);setRenamingSong(true)}}}>Rename current song</button></div></aside>
  <section className="center-panel"><div className="song-toolbar"><div className="song-ident"><div className="song-icon"><FileMusic size={19}/></div><div>{renamingSong?<input className="rename-input" value={title} onChange={e=>setTitle(e.target.value)} onBlur={rename} onKeyDown={e=>e.key==='Enter'&&rename()} autoFocus/>:<><h1>{song?.title??'Choose a song to begin'}</h1><p>{song?`${song.tracks.length} tracks · ${song.measures.length} measures · ${song.tempoMap[0]?.bpm.toFixed(0)??120} BPM`: 'Import a MIDI file to start practicing'}</p></>}</div></div><div className="toolbar-actions"><button className="subtle-button" disabled title="MIDI export is planned for a later phase"><ArrowDownToLine size={14}/> Export MIDI</button><button className="icon-button" title="Open file" onClick={()=>inputRef.current?.click()}><FolderOpen size={17}/></button></div></div>
   <div className="score-card"><div className="score-meta"><div className="score-heading"><BookOpen size={15}/><span>SHEET MUSIC</span><span className="score-sep"/> <span className="score-meta-muted">{measures?`${measures} measures`:'—'}</span></div><div className="score-actions"><span className="zoom-label">100%</span><button className="mini-button" title="Download sheet music PDF" disabled={!song} onClick={()=>song&&void import('../notation/exportPdf').then(m=>m.downloadSheetMusicPdf(song)).catch(e=>setDeviceError(e instanceof Error?e.message:'PDF export failed.'))}><ArrowDownToLine size={14}/> PDF</button></div></div><div className="score-area">{song?<Suspense fallback={<div className="score-loading">Loading notation…</div>}><ScoreView song={song} currentIds={visibleIds} playedIds={[]}/></Suspense>:<div className="empty-score"><div className="empty-music"><Music2 size={30}/></div><b>Your score will appear here</b><span>Import a MIDI file to see its notes as sheet music.</span><button className="primary-button" onClick={()=>inputRef.current?.click()}><Upload size={15}/> Import MIDI</button></div>}</div><div className="score-footer"><span><span className="legend-dot expected-dot"/>Expected note</span><span><span className="legend-dot played-dot"/>Played correctly</span><span className="score-tip"><Keyboard size={13}/> Connect a MIDI keyboard to practice</span></div></div>
   <div className="practice-card"><div className="practice-top"><div className="mode-tabs"><button className={mode==='practice'?'active':''} onClick={()=>selectMode('practice')}>Practice</button><button className={mode==='follow'?'active':''} onClick={()=>selectMode('follow')}>Follow</button><button className={mode==='playback'?'active':''} onClick={()=>selectMode('playback')}>Playback</button></div><div className="practice-tools"><button className="tool-button" disabled title="Looping is planned for a later phase"><span className="loop-mark">↻</span> Loop</button><button className="tool-button" disabled title="Metronome is planned for a later phase"><Volume2 size={15}/> Metronome</button><select aria-label="Hand selection" value={hand} onChange={e=>selectHand(e.target.value as HandSelection)}><option value="both">Both hands</option><option value="right">Tune · right hand</option><option value="left">Bass · left hand</option></select></div></div>
    <div className="transport"><div className="transport-buttons"><button className="transport-small" title="Previous event" onClick={()=>step(-1)}><ChevronLeft size={16}/></button><button className="play-button" title={playing?'Pause playback':'Play song'} onClick={()=>{if(mode!=='playback')selectMode('playback');void togglePlayback();}}>{playing?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}</button><button className="transport-small" title="Restart" onClick={restart}><RotateCcw size={15}/></button><button className="transport-small" title="Stop" onClick={restart}><Square size={13}/></button><button className="transport-small" title="Next event" onClick={()=>step(1)}><ChevronRight size={16}/></button></div><div className="progress-block"><div className="progress-copy"><span>{mode==='playback'?`PLAYBACK ${Math.floor(playbackTime/60)}:${String(Math.floor(playbackTime%60)).padStart(2,'0')}`:current?`EVENT ${engine!.index+1} / ${engine!.groups.length}`:song?'FINISHED':'READY'}</span><b>{Math.round(progress*100)}%</b></div><div className="progress-track"><div style={{width:`${progress*100}%`}}/></div></div><div className="tempo-control"><button onClick={()=>changeTempo(tempo-5)}>−</button><div><small>SPEED</small><b>{tempo}<small>%</small></b></div><button onClick={()=>changeTempo(tempo+5)}>+</button></div></div>
   </div>
   <div className="keyboard-card"><div className="keyboard-heading"><div><Keyboard size={15}/><span>FALLING NOTES</span><small>{mode==='playback'?'Time-synced playback':flash==='correct'?'Correct!':flash==='wrong'?'Try again':connected?'MIDI input active':'Play the highlighted notes'}</small></div><span className="keyboard-octaves">A0 — C8 · scroll to explore</span></div><KeyboardDeck expected={visibleExpected} played={played} correct={flash==='correct'?played:[]} wrong={flash==='wrong'?played:[]} mode={mode} groups={engine?.groups??[]} notes={handNotes} eventIndex={engine?.index??0} playbackTime={playbackTime}/></div>
  </section>
  <aside className="settings-panel"><div className="panel-heading settings-heading"><div><div className="eyebrow">SETUP</div><h2>Practice setup</h2></div><Settings size={17}/></div><section className="setup-section"><div className="section-title"><span className="section-icon"><Wifi size={15}/></span><b>MIDI DEVICE</b><span className={`connection-state ${connected?'online':''}`}><i/>{connected?'CONNECTED':'NOT CONNECTED'}</span></div><div className="device-box"><div className={`device-symbol ${connected?'device-active':''}`}><Keyboard size={18}/></div><div className="device-info"><b>{connected?(devices.find(d=>d.id===selectedDevice)?.name??devices[0]?.name??'MIDI keyboard'):'No device found'}</b><span>{pedalDown?'Sustain pedal down':connected?'Ready for input':'Connect a keyboard via USB'}</span></div></div>{devices.length>1&&<select className="device-select" aria-label="Select MIDI device" value={selectedDevice} onChange={e=>{setSelectedDevice(e.target.value);void setupMidi(e.target.value);}}><option value="">All MIDI inputs</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>}<button className={`connect-button ${connected?'connected-button':''}`} onClick={()=>connected?(cleanup.current?.(),setConnected(false),setPedalDown(false)):void setupMidi()}><Power size={14}/>{connected?'Disconnect':'Connect MIDI keyboard'}</button>{deviceError&&<p className="error-message">{deviceError}</p>}<small className="browser-note">Web MIDI works best in Chrome or Edge.</small></section>
   <section className="setup-section settings-options"><div className="section-title"><span className="section-icon purple"><Activity size={15}/></span><b>SESSION SETTINGS</b></div><label className="setting-row"><span><b>Practice mode</b><small>Follow highlights each played event</small></span><select value={mode} onChange={e=>selectMode(e.target.value as Mode)}><option value="practice">Practice</option><option value="follow">Follow</option><option value="playback">Playback</option></select></label><label className="setting-row"><span><b>Part to practice</b><small>Choose melody or bass</small></span><select aria-label="Part to practice" value={hand} onChange={e=>selectHand(e.target.value as HandSelection)}><option value="both">Both</option><option value="right">Tune · right</option><option value="left">Bass · left</option></select></label><div className="setting-row tempo-setting"><span><b>Playback speed</b><small>Adjust song playback</small></span><span className="tempo-value">{tempo}%</span></div><input className="tempo-range" type="range" min="50" max="150" value={tempo} onChange={e=>changeTempo(+e.target.value)}/><label className="setting-row"><span><b>Metronome</b><small>Coming in a later phase</small></span><button className="toggle" disabled><i/></button></label><label className="setting-row"><span><b>Loop section</b><small>Coming in a later phase</small></span><button className="toggle" disabled><i/></button></label></section>
   <section className="session-info"><div><Clock3 size={14}/><span>Progress</span><b>{Math.round(progress*100)}%</b></div><div className="mini-progress"><i style={{width:`${progress*100}%`}}/></div><p>{noteCount} notes across {measures} measures</p></section>
   <button className="help-link"><CircleHelp size={14}/> MIDI connection help <ChevronRight size={14}/></button>
  </aside>
 </main><footer className="statusbar"><span><span className="status-led"/> All changes saved locally</span><span className="status-right"><Headphones size={13}/> PianoPractice <i/> v0.1.0</span></footer>
 </div>
}

