import {describe,it,expect} from 'vitest';import {PracticeEngine,defaultPolicy,groupEvents,matchPitch,isWithinTimingTolerance} from './engine';import type {Song,SongNote} from '../model/song';
const note=(id:string,pitch:number,tick:number):SongNote=>({id,pitch,startTick:tick,durationTicks:240,startTime:tick/960,duration:.25,velocity:0.8,trackId:'t'});
const song=(notes:SongNote[]):Song=>({id:'s',title:'test',ppq:480,tracks:[{id:'t',name:'Piano',instrument:0,channel:0,notes}],tempoMap:[{tick:0,bpm:120}],timeSignatures:[{tick:0,numerator:4,denominator:4}],keySignatures:[],pedalEvents:[],measures:[{index:0,startTick:0,endTick:1920,startTime:0}],createdAt:0});
describe('practice matching',()=>{
 it('matches exact pitch and optionally ignores octave',()=>{expect(matchPitch(60,60,defaultPolicy)).toBe(true);expect(matchPitch(60,72,defaultPolicy)).toBe(false);expect(matchPitch(60,72,{...defaultPolicy,octaveTolerance:true})).toBe(true);});
 it('groups simultaneous pitches as a chord without pitch-order dependence',()=>{const groups=groupEvents([note('b',64,0),note('a',60,2),note('c',67,200)],12);expect(groups).toHaveLength(2);const engine=new PracticeEngine(song([note('c',60,0),note('e',64,0)]));expect(engine.input([64,60]).correct).toBe(true);expect(engine.done).toBe(true);});
 it('waits for a correct event and advances deterministically',()=>{const e=new PracticeEngine(song([note('a',60,0),note('b',62,480)]));expect(e.input([61]).correct).toBe(false);expect(e.index).toBe(0);expect(e.input([60]).correct).toBe(true);expect(e.current?.[0].pitch).toBe(62);expect(e.input([62]).correct).toBe(true);expect(e.done).toBe(true);});
 it('separates the melody and bass with middle C as the fallback split',()=>{const tune=new PracticeEngine(song([note('c4',60,0),note('c3',48,0),note('c5-left',72,480)]),undefined,'right');const bass=new PracticeEngine(song([note('c4',60,0),note('c3',48,0),note('c5-left',72,480)]),undefined,'left');expect(tune.groups.flat().map(n=>n.id)).toEqual(['c4','c5-left']);expect(bass.groups.flat().map(n=>n.id)).toEqual(['c3']);});
 it('accepts timing deviations only inside the configured tolerance',()=>{const strict={...defaultPolicy,timingToleranceMs:0},lenient={...defaultPolicy,timingToleranceMs:120};expect(isWithinTimingTolerance(1050,1000,strict)).toBe(false);expect(isWithinTimingTolerance(1050,1000,lenient)).toBe(true);expect(isWithinTimingTolerance(1201,1000,lenient)).toBe(false);});
});
